apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: self-healing-hpa-backend
  namespace: self-healing-system-namespace

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: self-healing-deployment-backend
  
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 700
