apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: self-healing-system-namespace
spec:
  selector:
    app: self-healing-system-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
