name: Automate deployment to Kubernetes

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BACKEND_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/self-healing-backend:v2
  FRONTEND_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/self-healing-frontend:v2
  NAMESPACE: self-healing-system-namespace

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    outputs:
      gen_img: ${{ steps.gen_img.outputs.gen_img }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Unique Image Name
        id: gen_img
        run: |
          TAG=$(git rev-parse --short HEAD)-$(date +%H%M%S) |
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Login Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Start Docker build
        run: |
          docker build -t ${{ env.BACKEND_IMAGE_NAME }}:${{ steps.gen_img.outputs.gen_img }} ./backend
          docker build -t ${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.gen_img.outputs.gen_img }} ./frontend

      - name: Push Docker image
        run: |
          docker push ${{ env.BACKEND_IMAGE_NAME }}:${{ steps.gen_img.outputs.gen_img }}
          docker push ${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.gen_img.outputs.gen_img }}

  load-image:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Confirm Minikube is running
        run: minikube status || (echo "Minikube is not running — start it before this job can proceed" && exit 1)

      - name: Load image into Minikube
        run: |
          minikube image load ${{ env.BACKEND_IMAGE_NAME }}:${{ needs.build-and-push.outputs.gen_img }} -n {{ env.NAMESPACE }}
          minikube image load ${{ env.FRONTEND_IMAGE_NAME }}:${{ needs.build-and-push.outputs.gen_img }} -n {{ env.NAMESPACE }}

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/self-healing-deployment-backend self-healing-system-backend=${{ env.BACKEND_IMAGE_NAME }} -n ${{ env.NAMESPACE }}
          kubectl set image deployment/self-healing-deployment-frontend self-healing-system-frontend=${{ env.FRONTEND_IMAGE_NAME }} -n ${{ env.NAMESPACE }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/self-healing-deployment-backend -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/self-healing-deployment-frontend -n ${{ env.NAMESPACE }}
